"""Initial migration

Revision ID: 1b1067d8f789
Revises: 
Create Date: 2025-08-04 01:48:33.349250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1067d8f789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=True),
    sa.Column('synopsis', sa.TEXT(), nullable=True),
    sa.Column('poster_url', sa.VARCHAR(length=300), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=300), nullable=True),
    sa.Column('director', sa.VARCHAR(length=100), nullable=True),
    sa.Column('runtime', sa.INTEGER(), nullable=True),
    sa.Column('imdb_rating', sa.FLOAT(), nullable=True),
    sa.Column('added_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###
